- app/models/setting.rb
- app/views/admin/settings/index.html.erb
* Create less overhead in the .get method, by using .pluck() instead of .find_by().value
* Prevent link preloaders from causing setting-removal chaos, by using DELETE instead of GET for the delete link.
> More efficient .get(), less dangerous .delete()

- app/controllers/admin/settings_controller.rb
The tests seem to show that the validation fail check is enough to keep us safe here; no need to rescue.
> Remove unneeded rescue block

- spec/factories/capabilities.rb
- spec/factories/capability_categories.rb
- spec/factories/feature_flags.rb
- spec/factories/page_elements.rb
- spec/factories/page_sections.rb
- spec/factories/page_template_elements.rb
- spec/factories/page_templates.rb
- spec/factories/pages.rb
- spec/factories/settings.rb
- spec/factories/shared_content_elements.rb
- spec/support/faker.rb
I kept getting test failures from element names like 'tin' and similar colliding with parts of words on my pages (in expect(...).not_to include(...) tests), which was tedious. So, Lorem; it's not as much fun as Science, but it's less likely to contain parts of real words. Meh.
> Fix Faker uniqueness

- app/controllers/admin/pages/sections_controller.rb
- app/controllers/admin/pages/templates_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/admin/settings_controller.rb
- app/controllers/admin/shared_content_controller.rb
- app/controllers/admin/users_controller.rb
- app/views/admin/pages/edit.html.erb
- app/views/admin/pages/index.html.erb
- app/views/admin/pages/new.html.erb
- app/views/admin/pages/sections/edit.html.erb
- app/views/admin/pages/sections/new.html.erb
- app/views/admin/pages/templates/edit.html.erb
- app/views/admin/pages/templates/index.html.erb
- app/views/admin/pages/templates/new.html.erb
- app/views/admin/settings/index.html.erb
- app/views/admin/shared_content/index.html.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/index.html.erb
- app/views/admin/users/new.html.erb
- config/locales/en.yml
- spec/request/admin/pages/sections_spec.rb
- spec/request/admin/pages/templates_spec.rb
- spec/request/admin/pages_spec.rb
- spec/request/admin/settings_spec.rb
- spec/request/admin/shared_content_spec.rb
- spec/request/admin/users_spec.rb
- spec/request/admin_spec.rb
Change all the create/update/delete success/failure messages to have success/failure as the key, and the page titles to all have title as the key. Consistency FTW.
> More consistent page title and alert message i18n keys

- spec/factories/blog_posts.rb
- spec/factories/blogs.rb
- spec/factories/capabilities.rb
- spec/factories/capability_categories.rb
- spec/factories/comments.rb
- spec/factories/feature_flags.rb
- spec/factories/insert_elements.rb
- spec/factories/news_posts.rb
- spec/factories/page_elements.rb
- spec/factories/page_sections.rb
- spec/factories/page_template_elements.rb
- spec/factories/page_templates.rb
- spec/factories/pages.rb
- spec/factories/setting_values.rb
- spec/factories/settings.rb
- spec/requests/admin/blog/posts_spec.rb
- spec/requests/admin/blogs_spec.rb
- spec/requests/admin/news_spec.rb
- spec/requests/admin/pages/sections_spec.rb
- spec/requests/admin/pages/templates_spec.rb
- spec/requests/admin/pages_spec.rb
- spec/requests/blogs_spec.rb
- spec/requests/news_spec.rb
(Also, this flushed out some tests that were fragile around content with apostrophes in. Fixed by replacing 'include' expectations with 'have_css' expectations, which presumably encodes/decodes entities the same way that Rails does.)
> CultureSeries.culture_ship <3

- Gemfile
- config/environments/production.rb
- config/initializers/ahoy.rb
- tools/heroku-release
* Move dotenv into production area of Gemfile (rake tasks need it)
* Remove geocoding support from Ahoy stats for now - it's broken, something about licensing
* Disable forgery protection in production - not sure if this is controversial or not? It false positives a lot at work, fills our logs with crap. It seems to cope badly with proxies? It doesn't like my slightly gaffer-taped Heroku+Cloudflare SSL config, anyway.
> Heroku-related tweaks and fixes

- app/controllers/tags_controller.rb
- app/views/shinycms/tags/show.html.erb
* Add 'no tagged content found' section to template
* Update controller to use taggable? method to identify tagged content models, rather than maintaining a static list of content types
> Minor improvements to Tags feature

- spec/requests/admin/comments_spec.rb
> Skip tests that require an Akismet key unless one is set in ENV

- app/controllers/admin/comments_controller.rb
- app/helpers/main_site_helper.rb
- app/models/application_record.rb
- app/models/blog_post.rb
- app/models/comment.rb
- app/models/news_post.rb
- app/views/admin/blog/posts/index.html.erb
- app/views/admin/news/index.html.erb
- app/views/shinycms/blogs/_post_in_list.erb
- app/views/shinycms/blogs/_post_in_list_header.erb
- app/views/shinycms/menu/_blog.html.erb
- app/views/shinycms/news/index.html.erb
- app/views/shinycms/news/month.html.erb
- app/views/shinycms/news/show.html.erb
- app/views/shinycms/news/year.html.erb
- app/views/shinycms/tags/show.html.erb
- config/routes.rb
- spec/requests/admin/comments_spec.rb
Keeps the code cleaner by:
* Keeping the path-generation code closer to each object, rather than a big if/elsif blocks in the helper
* Leveraging the routes file definition rather than reimplementing it in the helper
> Refactor path helpers for news posts and blog posts

- app/models/page_template.rb
- lib/tasks/demo.rake
* rails shiny:demo:load needs to set theme_name SettingValue before it tries to create PageTemplate records (otherwise the test for the template file existing on disk will fail)
* When no theme name is set, there is no page templates directory available - so template_dir and available_templates are both blank
> Fix two bugs relating to when theme_name isn't set (fixes #321)

- spec/models/discussion_spec.rb
Pinned down wobbly test - due to one of the created discussions sometimes having zero comments and hence not being 'active'. Added explicit test for this (correct) behaviour, and made sure it doesn't happen in the other tests to confuse them.
> Fix discussion tests (again)

- app/models/page.rb
- app/models/page_section.rb
- spec/models/page_section_spec.rb
- spec/models/page_spec.rb
> Use .implicit_order_column instead of default_scope to always sort by sort_order

- .circleci/config.yml
- .rubocop.yml
NB: Had to specify the directories to run Rubocop against, otherwise it insisted on checking all the faily gem code in the vendor/ directory no matter what my config excluded.
> Add rubocop and bundle audit to CircleCI config

- Gemfile.lock
- config/initializers/version.rb
- plugins/ShinyForms/lib/shiny_forms/version.rb
The August 2020 version of ShinyCMS brings us our first foray into plugin architecture, with the all-new, probably-functional ShinyForms plugin for adding contact forms etc to your ShinyCMS website.
> Bump version

- app/controllers/admin_controller.rb
- app/models/plugin.rb
:symbol.start_with? works in ruby 2.7.1 but not in 2.6.6 or earlier
> Convert symbols to strings before using .start_with? on them

- plugins/ShinyBlog/app/policies/shiny_blog/post_policy.rb
- plugins/ShinyForms/app/policies/shiny_forms/form_policy.rb
- plugins/ShinyNews/app/policies/shiny_news/post_policy.rb
- plugins/ShinyPages/app/policies/shiny_pages/page_policy.rb
- plugins/ShinyPages/app/policies/shiny_pages/section_policy.rb
- plugins/ShinyPages/app/policies/shiny_pages/template_policy.rb
Several of the existing plugins have the same error in their pundit policies (the add? method responds based on whether the user has permission to list, not add) which this PR fixes.
> Fix copypasta error in plugin pundit policies

- lib/tasks/demo.rake
- spec/support/shared_examples/shiny_post_example.rb
These are the actual code changes that Rubocop 2.8.0 required... before exploding in a shower of shrapnel that means it fails CI even when all the cops pass.
> Pre-emptive rubocop fixes

- docs/Developers/TODO.md
- spec/factories/users.rb
In particular, 'ed' manages to be a partial match for all kinds of longer test data, and hence breaks .not_to tests semi-regularly.
(The exact_match param (mentioned in removed section of TODO) unsurprisingly breaks with whitespace around the text, which is pretty unavoidable if you want readable HTML in your templates. Hence the alternative solution of a minimum username length.)
> Fix occasional false-positive test failures caused by short usernames

- docs/Developers/TODO.md
- plugins/ShinyPages/app/controllers/shiny_pages/admin/sections_controller.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin/templates_controller.rb
- plugins/ShinyPages/app/views/shiny_pages/admin/pages/new.html.erb
- plugins/ShinyPages/app/views/shiny_pages/admin/sections/new.html.erb
- plugins/ShinyPages/app/views/shiny_pages/admin/templates/new.html.erb
- plugins/ShinyPages/config/locales/en.yml
- plugins/ShinyPages/spec/requests/admin/pages_spec.rb
- plugins/ShinyPages/spec/requests/admin/sections_spec.rb
- plugins/ShinyPages/spec/requests/admin/templates_spec.rb
Inconsistent param naming between the new and edit actions for page sections and page templates meant that the edit feature for both was broken (failed at the strong params check).
> Fix page section+template edit actions

- app/helpers/shiny_date_helper.rb
- app/lib/shiny_discussion_admin.rb
- app/lib/shiny_post_admin.rb
- config/locales/en.yml
- plugins/ShinyBlog/app/controllers/shiny_blog/admin/blog_posts_controller.rb
- plugins/ShinyBlog/app/views/shiny_blog/admin/blog_posts/edit.html.erb
- plugins/ShinyBlog/app/views/shiny_blog/admin/blog_posts/new.html.erb
- plugins/ShinyBlog/spec/requests/admin/blog_spec.rb
- plugins/ShinyNews/app/controllers/shiny_news/admin/news_posts_controller.rb
- plugins/ShinyNews/app/views/shiny_news/admin/news_posts/edit.html.erb
- plugins/ShinyNews/app/views/shiny_news/admin/news_posts/new.html.erb
- plugins/ShinyNews/spec/requests/admin/news_spec.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/sends_controller.rb
Discussions weren't getting created when new blog or news posts were created. Now they do. :slightly_smiling_face: 
There's a bunch of refactoring in here to pull some common functionality out into a couple of admin libs, rather than copy-pasting discussion flag handling code into both admin controllers.
> Implement discussion creation

- lib/tasks/demo.rake
- plugins/ShinyNewsletters/spec/requests/admin/templates_spec.rb
- plugins/ShinyPages/spec/requests/admin/templates_spec.rb
- plugins/ShinySearch/spec/requests/search_spec.rb
- spec/requests/admin/comments_spec.rb
Fixing a few of the (but not all) of the include matchers mentioned in issue 158
> Use more specific matchers in request specs

- Gemfile
- app/models/shiny_plugin.rb
- docs/Developers/TODO.md
- tools/heroku-release
- tools/shiny-bundle-install
- tools/shiny-sidekiq-dev
* Handle wonky requested plugin lists more gracefully (ignore ones we don't have, ignore duplicates)
* Add wrapper script for running `bundle install` with ENV loaded - so we can look at SHINYCMS_PLUGINS and only install what was asked for)
* Add wrapper script for running sidekiq in dev with ENV loaded too, to pick up possible config from there
> Make Plugin-loading Great Again

- app/models/ahoy/event.rb
- app/models/ahoy/message.rb
- app/models/ahoy/visit.rb
- app/models/concerns/shiny_email.rb
- app/models/do_not_contact.rb
- docs/Developers/TODO.md
Strip whitespace from emails before we save them, in case of bad input data (seen in the wild from bots, meh).
> Strip emails

- app/controllers/discussions_controller.rb
- spec/requests/discussions_spec.rb
A slight mis-use of ActiveRecord meant that we were still creating CommentAuthor records (and EmailRecipient, and hence confirmation email jobs) even if the actual comment was so obviously spam that we didn't bother to put it in the database itself.
> Ignore blatant spammers

- Gemfile
- Gemfile.lock
- docs/Developers/TODO.md
Their recent release got rid of the deprecation warnings on Rails 6.1
> Back to rubygems for acts_as_votable

- .rubycritic.yml
- Gemfile
- Gemfile.lock
- app/models/concerns/shiny_post.rb
- app/models/shiny_plugin.rb
- app/models/shiny_post_atom_feed.rb
- config/rails_best_practices.yml
- docs/Developers/Notes/ruby-3.0.0.md
- docs/Developers/TODO.md
Had to leave the gem itself commented out in the Gemfile for now, as reek's dependencies haven't caught up with Ruby 3.0 yet... but it's all ready to go once that's sorted out, and you can `gem install rubycritic` in the meantime.
> Add config for Ruby Critic

- app/models/concerns/shiny_user_authentication.rb
- app/models/concerns/shiny_user_authorization.rb
- app/models/concerns/shiny_user_content.rb
- app/models/user.rb
Peel off authentication (Devise), authorization (Pundit), and main app content associations (stats, comments, etc) into three separate concerns. No functional changes, just locating the code in separate files, that could theoretically be loaded (or not loaded) selectively.
This is part of my thinking about how to make all of ShinyCMS modular, so people can bolt it (or selected bits of it) onto any other Rails app. Probably one that already uses Devise, so they might not want all of the ShinyCMS User model stuff if it duplicates/clashes with their own.
> Break user model up

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- app/controllers/users/passwords_controller.rb
- config/routes.rb
- docs/Developers/TODO.md
- spec/requests/users/passwords_controller_spec.rb
- spec/requests/users/registrations_controller_spec.rb
- spec/requests/users/sessions_controller_spec.rb
This PR just creates (and tests) the endpoint; it's not being used in the registration/etc flows yet.
Also refactored the existing user controller tests a little (split up registration and session tests).
> Add password scoring endpoint, powered by zxcvbn

- Gemfile
- Gemfile.lock
- docs/Developers/TODO.md
This was left out before to make Travis CI multi-ruby-version job work, but as they are no longer relevant...
Re-adding this means that Heroku actually uses the correct version of Ruby now, yay (they ignore .ruby-version for some reason).
> Add explicit Ruby version to Gemfile

- app/models/concerns/shiny_mjml_template.rb
- app/validators/mjml_syntax_validator.rb
- package.json
- yarn.lock
The validator calls out to `mjml --validate` directly now, instead of calling `Mjml::Parser.render` and catching the exception when invalid.
This change is compatible with MJML 4.8.x, so that's been unpinned and updated.
> Rewrite MJML validator

- .rspec
- .rspec_parallel
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- tools/bundle-install
- tools/heroku-release
- tools/parallel-rspec
- tools/sidekiq-dev
* Fix rspec config so the bare `rspec` command will run the plugin tests as well as the main app tests
* Output failure details immediately during test runs, inline with the progress dots, as well as at the end of the run ("Fail early! Fail often!")
* Create more log files when running `tools/parallel-rspec` (failure log and summary log as well as timing log)
> Some improvements to rspec config

- config/routes.rb
- plugins/ShinyCMS/app/controllers/shinycms/errors_controller.rb
- plugins/ShinyCMS/config/routes/php_is_a_bad_request.rb
- plugins/ShinyCMS/spec/requests/shinycms/errors_controller_spec.rb
(Wordpress h4xx0rz trollolol oh god my logs)
I put the route immediately after the root path in the main routes file. Your priorities may differ.
This catches anything ending in .php ... which mostly means script kiddies looking for unsecured Wordpress installs.
It returns a headers-only 400 (bad request) error, for minimum cost to us.
> Drop all URLs ending in .php

- plugins/ShinyCMS/app/models/concerns/shinycms/element.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/has_template.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/provides_demo_site_data.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/template_element.rb
- plugins/ShinyCMS/app/models/shinycms/comment.rb
- plugins/ShinyCMS/app/models/shinycms/discussion.rb
- plugins/ShinyCMS/app/models/shinycms/pseudonymous_author.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/send.rb
- plugins/ShinyPages/spec/factories/shiny_pages/template_elements.rb
- plugins/ShinyPages/spec/models/shiny_pages/template_element_spec.rb
- plugins/ShinyProfiles/app/models/shiny_profiles/link.rb
Something wasn't quite working right in the previous incarnation of this (relating to module load order, I think). I've rewritten it to use a different method name for the override method and the default method, so that part of it is more explicit about what it's doing now.
> Rewrite demo data load order config methods

- plugins/ShinyCMS/app/models/concerns/shinycms/has_tags.rb
- plugins/ShinyCMS/app/models/shinycms/plugins.rb
- plugins/ShinyCMS/spec/controllers/concerns/shinycms/admin/tags_spec.rb
I got this down to an admittedly action-packed (AKA dense, bordering on obfuscated) three line method which was a continuous chain of method calls. Ruby Critic said it was too complex.
So I split that into three methods, one for each line more or less. Ruby Critic said they were too trivial. 😝 
I kept the version with three methods, because I quite liked how the method names and variable names had ended up. One bot's trivial is another man's 'easy to reason about', right? 😉  
Also, I jammed the acts-as-taggable-on fix into this branch because I am a terrible person. It wasn't actually set to preserve order, I must have just got lucky up to now? Weirdness. Anyway, should be sorted now.
> Refactor build_plugins_from_names method

- plugins/ShinyCMS/app/models/shinycms/comment.rb
- plugins/ShinyCMS/app/views/shinycms/discussions/comment/_posted_by.html.erb
Methods in comments model, being used in discussion/comment partials. Fixes a couple of errors that have been coming up on shinycms.org this week...
> Methods to identify each comment author type

- package.json
- yarn.lock
This is stuck at the far end of a long chain of webpacker dependencies. #standard
> Explicitly require latest is-svg

- Gemfile
- Gemfile.lock
- config/initializers/version.rb
- docs/Developers/Plugins.md
- docs/release-notes.md
- plugins/ShinyAccess/lib/shiny_access/version.rb
- plugins/ShinyBlog/lib/shiny_blog/version.rb
- plugins/ShinyCMS/lib/shinycms/version.rb
- plugins/ShinyForms/lib/shiny_forms/version.rb
- plugins/ShinyInserts/lib/shiny_inserts/version.rb
- plugins/ShinyLists/lib/shiny_lists/version.rb
- plugins/ShinyNews/lib/shiny_news/version.rb
- plugins/ShinyNewsletters/lib/shiny_newsletters/version.rb
- plugins/ShinyPages/lib/shiny_pages/version.rb
- plugins/ShinyProfiles/lib/shiny_profiles/version.rb
- plugins/ShinySEO/lib/shiny_seo/version.rb
- plugins/ShinySearch/lib/shiny_search/version.rb
Main addition (and cause of some fairly major code shuffling) in this release is [Packwerk](https://github.com/Shopify/packwerk/blob/main/README.md) to enforce plugin boundaries.
Also added routes partials, bullet (N+1 query detection), CodeClimate coverage reporting, and the Items extension for Pagy (although the front-end widget for that refuses to work, yay JavaScript).
Plus lots of improvements to base controllers and mailers (now in the core plugin's app/public area), and moved Rails Email Preview engine, rubocop config, and ShinyCMS rake tasks, from main_app into the core plugin.
> April 2021: The 'Respecting Boundaries' release

- themes/halcyonic/stylesheets/halcyonic/shinycms.scss
(These CSS changes aren't carrying through to staging in a branch deployment, but I can't see why not, so I'm going to merge it as is for now and go back to working in the View Components branch for a bit.)
> Fix some more accessibility issues in the Halcyonic theme; mostly contrast ratios

- Gemfile
- Gemfile.lock
- tools/mutate
Adding [mutant](https://github.com/mbj/mutant#readme) gem for mutation testing (with an open source licence kindly provided by the author, thank you @mbj!)
Currently there is just a script to run `mutant` over a specific class or plugin. I'm pretty sure there is a lot more that could be done with this now that it's included; the mutant readme suggests viewing it as a code review tool rather than a test coverage tool - with each mutation that passes tests either showing a missing test _or showing code that could be simplified_.
> Mutation testing

- docs/Configuration.md
Gudday!
While reading through the configuration documentation, I noticed some text elements which clashed with the markdown formatting.  It seemed best to format these elements as code since they were code-like things in the text and formatting them as such removed the clashes with markdown.  I also spotted a duplicate word, which I removed in a separate commit.  I also thought it might be handy for the reader to have a link to `Devise::PwnedPassword`, hence I added a link to the project's GitHub repo.  If you'd like such changes to be submitted in a separate PR, please just let me know :-)
I've split the changes into separate commits so that you can cheery-pick them if you so wish.  This PR is submitted in the hope that it is helpful; if you'd like anything changed or fixed, please don't …
> Add formatting to configuration docs

- plugins/ShinyCMS/app/views/shinycms/admin/layouts/admin_area.html.erb
- public/js/shinycms/admin_area.js
This is a temporary fix for issues caused (in production only) by moving some admin area JS code from <script> tags in a view template to a separate .js file.
(I swear I could have written at least two more feature plugins in the time I've wasted f*&#ing around with JavaScript config files in this project so far) 😞
> Move admin area JS sprinkles into /public for now

- db/seeds.rb
- docs/Licensing/index.md
- docs/release-notes.md
- lib/templates/shiny/plugin/README.md.tt
- mkdocs.yml
- plugins/ShinyAccess/README.md
- plugins/ShinyBlog/README.md
- plugins/ShinyCMS/.rubocop_todo.yml
- plugins/ShinyCMS/README.md
- plugins/ShinyCMS/app/components/shinycms/toolbar/discussions_component.rb
- plugins/ShinyCMS/app/components/shinycms/toolbar/users_component.rb
- plugins/ShinyCMS/app/views/shinycms/includes/_footer.html.erb
- plugins/ShinyCMS/config/initializers/assets.rb
- plugins/ShinyForms/README.md
- plugins/ShinyInserts/README.md
- plugins/ShinyLists/README.md
- plugins/ShinyNews/README.md
- plugins/ShinyNewsletters/README.md
- plugins/ShinyPages/README.md
- plugins/ShinyProfiles/README.md
- plugins/ShinySEO/README.md
- plugins/ShinySearch/README.md
Mostly just a whole bunch of gem updates from the last 3 years, including pretty much all of the most significant ones the CMS uses.
> Release gem updates since 2021 as 24.11

- config/initializers/sidekiq.rb
Can't rely on the default settings any more, they're throwing errors at unsigned keys on Heroku
> Add explicit sidekiq/redis initializer

- .circleci/config.yml
Switch to newer CircleCI images for postgres (cimg/... instead of circleci/...).
No ramdisk variant any more, but doesn't seem to make that much difference.
> Update CircleCI postgres

- Gemfile
- Gemfile.lock
- plugins/ShinyAccess/shiny_access.gemspec
- plugins/ShinyBlog/shiny_blog.gemspec
- plugins/ShinyCMS/app/views/shinycms/includes/_newer_older_pager.html.erb
- plugins/ShinyCMS/config/initializers/pagy.rb
- plugins/ShinyCMS/shinycms.gemspec
- plugins/ShinyForms/shiny_forms.gemspec
- plugins/ShinyInserts/shiny_inserts.gemspec
- plugins/ShinyLists/shiny_lists.gemspec
- plugins/ShinyNews/shiny_news.gemspec
- plugins/ShinyNewsletters/shiny_newsletters.gemspec
- plugins/ShinyPages/shiny_pages.gemspec
- plugins/ShinyProfiles/shiny_profiles.gemspec
- plugins/ShinySearch/shiny_search.gemspec
Pagy gem updated from 6.5.0 to 8.6.3 (via 7.0.11, 8.0.2 and 8.1.2), with whatever changes were required to its usage along the way.
8.6.3 is the last release in their 'legacy' docs; next step is 9.0(.9), and from there up to 9.3(.4) which is their current release.
> Upgrade Pagy (legacy edition)

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/config/initializers/rack_attack.rb
- plugins/ShinyCMS/spec/requests/shinycms/errors_controller_spec.rb
- tools/mutate
Just catching the two most common WordPress admin URLs here for now, but might be worth expanding on this at a later date.
> Add very simple rack::attack filtering

- plugins/ShinyCMS/config/initializers/rack_attack.rb
After blocking wp-admin, wp-login, and wp-content yesterday, another piece of WordPress crap floated to the top of my logging this morning...
> Add wp-includes to the list of WordPress crap to ignore

- plugins/ShinyCMS/config/initializers/pagy.rb
Remove pagy plugin that hides the URL param for page 1, because it started interacting badly with the code to translate paging links from path?param=value to path/param/value and vice versa.
> Fix pagy issues

- README.md
I'm not sure if I keep forgetting to update these numbers in various places, or if I'm overwriting them somehow. 🙄
> Fix Ruby and Rails versions in docs

- themes/halcyonic/stylesheets/halcyonic/shinycms.scss
- themes/halcyonic/views/includes/_footer.html.erb
At some point in the Rails 6-7-8 upgrade journey the logout link stopped working. This PR gets it working again, by changing it from a link to a button (styled to still look like a link).
> Change logout link to logout button

- plugins/ShinyCMS/.rubocop.yml
Rubocop gems for Capybara and RSpec Rails are invoked with plugin syntax now.
> Change two more rubocop requires to plugins

- plugins/ShinyCMS/config/initializers/bugsnag.rb
- plugins/ShinyCMS/config/initializers/sentry.rb
Ignore all 404 errors on BugSnag, so anything else that goes wrong over there stands out from the incessant noise of blind bot attacks aimed at WordPress sites.
> Add initialiser for BugSnag

- plugins/ShinyCMS/.rubocop_todo.yml
- plugins/ShinyCMS/spec/models/shinycms/discussion_spec.rb
- plugins/ShinyCMS/spec/requests/shinycms/admin/comments_controller_spec.rb
- plugins/ShinyCMS/spec/requests/shinycms/comments_controller_spec.rb
- plugins/ShinyForms/spec/requests/shiny_forms/forms_controller_spec.rb
Fix #846 - (Fixed the two first files for AnyInstance (spec/requests/shinycms/admin/comments_controller_spec.rb and spec/requests/shinycms/comments_controller_spec.rb) and the first file for InstanceVariable (spec/models/shinycms/discussion_spec.rb)).
> Fix rubocop-rspec warnings for RSpec/InstanceVariable and RSpec/AnyInstance
