- app/assets/stylesheets/admin-area.css
- app/views/admin/includes/_breadcrumbs.html.erb
- app/views/admin/includes/_head.html.erb
- app/views/admin/includes/_menu.html.erb
- app/views/admin/includes/_messages.html.erb
- app/views/includes/_head.html.erb
- app/views/layouts/admin-area.html.erb
- config/initializers/assets.rb
Some basic styling, until I get around to refitting the full templates etc.
> Basic styling for admin area, kept separate from main site

- .rubocop.yml
- spec/request/pages_spec.rb
AllCops:
EnabledByDefault: true
> Rubocop all the things!

- app/controllers/admin/pages/sections_controller.rb
- app/controllers/admin/pages/templates_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/pages_controller.rb
- app/models/page.rb
- app/models/page_section.rb
- app/models/page_template.rb
- spec/models/page_template_spec.rb
- spec/request/admin/pages/sections_spec.rb
- spec/request/admin/pages/templates_spec.rb
- spec/request/admin/pages_spec.rb
> Tests and validations for pages/sections/templates

- spec/request/admin/pages_spec.rb
> Add some extra tests for hidden items on the combined page+section list

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
Can I really comment all of these out and still have my application work?! Apparently so!
> REMOVE ALL THE THINGS !!!

- app/controllers/pages_controller.rb
- app/models/page_section.rb
- config/locales/en.yml
- spec/request/admin/pages/sections_spec.rb
- spec/request/admin/pages/templates_spec.rb
- spec/request/admin/pages_spec.rb
- spec/request/admin/settings_spec.rb
- spec/request/admin_spec.rb
- spec/request/pages_spec.rb
Also, removed an unused method on a model, and engaged in some more whitespace noodling in the tests.
> Fix handling of missing template files (and add test for it)

- spec/factories/page_sections.rb
- spec/factories/page_templates.rb
- spec/factories/pages.rb
- spec/factories/settings.rb
- spec/models/page_section_spec.rb
- spec/models/page_spec.rb
- spec/models/page_template_spec.rb
- spec/request/admin/pages/sections_spec.rb
- spec/request/admin/pages_spec.rb
- spec/request/pages_spec.rb
Not sure what fixed it exactly, but the slug munging seems to be working now. **shrug**
> Fix factory faker fails

- app/views/admin/pages/_section_contents.html.erb
> Fix tab/space mix

- app/controllers/application_controller.rb
- app/models/user.rb
... and stick a sneaky :nocov: around email sends that we don't do in test env (yet?)
> Remove unused user code

- app/controllers/admin/shared_content_controller.rb
- app/helpers/shared_elements_helper.rb
- app/views/admin/includes/_menu.html.erb
- app/views/admin/settings/index.html.erb
- app/views/admin/shared_content/index.html.erb
- app/views/pages/templates/example.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/factories/shared_elements.rb
- spec/request/admin/shared_content_spec.rb
- spec/request/shared_content_spec.rb
Adds an admin area page for creating and updating shared content.
> Shared content admin area

- app/controllers/admin/pages/templates_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/pages_controller.rb
- app/models/concerns/element.rb
- app/models/page.rb
- app/models/page_section.rb
- app/models/page_template.rb
- app/views/admin/pages/_page_element.html.erb
- app/views/admin/pages/edit.html.erb
- app/views/admin/pages/templates/index.html.erb
- app/views/pages/templates/example.html.erb
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- db/schema.rb
- spec/factories/page_elements.rb
- spec/factories/page_templates.rb
- spec/factories/pages.rb
- spec/models/page_section_spec.rb
- spec/models/page_template_spec.rb
- spec/request/admin/pages/templates_spec.rb
- spec/request/admin/pages_spec.rb
- spec/request/admin/settings_spec.rb
- spec/request/pages_spec.rb
- spec/request/user_spec.rb
* Page elements are now injected to the render process as locals, so the tags are just <%= element_name %>
* Template element creation moved from controller to model
* Templates can be deleted
* default_page code simplified
* Started adding content_type support to edit page for Pages
> Page admin and rendering improvements

- app/helpers/elements_helper.rb
- app/views/admin/includes/_admin_toolbar.html.erb
- app/views/admin/includes/_breadcrumbs.html.erb
- app/views/admin/includes/_head.html.erb
- app/views/admin/includes/_message.html.erb
- app/views/admin/includes/_messages.html.erb
- app/views/admin/pages/edit.html.erb
- app/views/admin/pages/index.html.erb
- app/views/admin/pages/new.html.erb
- app/views/admin/pages/sections/edit.html.erb
- app/views/admin/pages/sections/new.html.erb
- app/views/admin/pages/templates/edit.html.erb
- app/views/admin/pages/templates/index.html.erb
- app/views/admin/pages/templates/new.html.erb
- app/views/admin/settings/index.html.erb
- spec/request/admin/shared_content_spec.rb
Added a helper method for whether to load CKEditor, tidied up messages partial, fixed a couple of odd/inconsistent uses of path/url helper methods.
> Assorted minor fixes in admin area

- app/assets/stylesheets/halcyonic/shinycms.css
- app/models/page.rb
- app/views/themes/halcyonic/includes/_header.html.erb
- app/views/themes/halcyonic/layouts/halcyonic.html.erb
In particular, make alerts visible. Also, a helper method for figuring out when we're looking at the homepage.
> Minor fixes for main site

- app/views/admin/includes/_footer_javascript.html.erb
- app/views/admin/includes/_head.html.erb
- app/views/admin/menu/_menu.html.erb
- app/views/admin/menu/_menu_section_start.html.erb
- public/js/shinycms/menu_state.js
Still need to get this (and ckeditor config) to play nice with webpacker at some point.
> Move menu state js into separate file

- db/migrate/20190928090153_create_pages.rb
- db/migrate/20190928091301_create_page_sections.rb
- db/migrate/20190928091447_create_page_templates.rb
- db/migrate/20190929081354_add_keys_to_page.rb
- db/migrate/20191004223601_create_settings.rb
- db/migrate/20191014193220_devise_create_users.rb
- db/migrate/20191017200134_create_page_template_elements.rb
- db/migrate/20191017200135_create_page_elements.rb
- db/migrate/20191017200136_create_shared_content_elements.rb
- db/migrate/20191109152134_create_sessions.rb
- db/schema.rb
Also added 'show in menu' option to pages and page sections.
> Add 'if not exists' flag to migrations

- app/views/admin/menu/_menu__item.html.erb
- app/views/admin/menu/_menu__section_start.html.erb
More fun with the assets pipeline...
> Fix admin menu icons in production

- package.json
- yarn.lock
(and a few other things that got caught up in the excitement)
> Update serialize-javascript node module

- app/controllers/admin_controller.rb
- app/policies/admin_policy.rb
- config/locales/en.yml
- db/seeds.rb
Fix a couple of minor issues with the new Pundit code.
> Pundit tweaks

- app/assets/stylesheets/shinycms/admin_area.scss
- app/controllers/admin/users_controller.rb
- app/helpers/admin_area_helper.rb
- app/models/capability.rb
- app/models/user.rb
- app/views/admin/users/_capability_checkbox.html.erb
- app/views/admin/users/_edit_capabilities.html.erb
- app/views/admin/users/edit.html.erb
- db/migrate/20191217175907_add_index_to_user_capabilities.rb
- db/schema.rb
- spec/request/admin/users_spec.rb
> Update user capabilities from admin 'edit user' page

- app/controllers/users/registrations_controller.rb
- app/controllers/users_controller.rb
- app/views/admin/includes/_user_menu.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/themes/halcyonic/includes/_footer.html.erb
- app/views/themes/shinycms/includes/_footer.html.erb
- config/routes.rb
- spec/request/feature_flags_spec.rb
- spec/request/user_spec.rb
Use a more Devise-native way of overriding its routes, meaning that it should stick to the new ones more consistently.
> Override Devise routes more consistently

- spec/factories/capabilities.rb
- spec/factories/capability_categories.rb
- spec/factories/feature_flags.rb
- spec/factories/page_elements.rb
- spec/factories/page_sections.rb
- spec/factories/page_template_elements.rb
- spec/factories/page_templates.rb
- spec/factories/pages.rb
- spec/factories/settings.rb
- spec/factories/shared_content_elements.rb
- spec/support/faker.rb
> Fix faker collisions

- app/assets/stylesheets/halcyonic/shinycms.css
- app/controllers/application_controller.rb
- app/views/themes/halcyonic/includes/_footer.html.erb
- config/locales/en.yml
- spec/requests/admin/users_spec.rb
- spec/requests/user_spec.rb
... and add login form to bottom of Halcyonic theme pages
> Improve post-login redirect

- app/views/shinycms/blogs/month.html.erb
- app/views/shinycms/blogs/year.html.erb
- config/i18n-tasks.yml
- spec/requests/blogs_spec.rb
... and re-enable tests that check for them.
> Fix month names in blog month/year views

- app/views/shinycms/menu/_pages.html.erb
- app/views/shinycms/menu/_pages_section.html.erb
- app/views/themes/halcyonic/includes/_footer_javascript.html.erb
Only fixed first level of nesting for pages here, still need to recurse properly for deeper nesting.
> Fix main menu drop downs

- app/controllers/application_controller.rb
- app/models/blog.rb
- app/models/page_template.rb
- app/views/shinycms/blogs/month.html.erb
- spec/requests/blogs_spec.rb
- spec/requests/user_spec.rb
Picking up some odds and ends from previous code reviews and GitHub comments...
> Fixes from code reviews

- db/demo-site-data/blog_posts.yml
- db/demo-site-data/blogs.yml
- db/demo-site-data/capabilities.yml
- db/demo-site-data/capability_categories.yml
- db/demo-site-data/feature_flags.yml
- db/demo-site-data/insert_sets.yml
- db/demo-site-data/page_elements.yml
- db/demo-site-data/page_sections.yml
- db/demo-site-data/pages.yml
- db/demo-site-data/setting_values.yml
- db/demo-site-data/settings.yml
- db/demo-site-data/user_capabilities.yml
- db/demo-site-data/users.yml
- tools/dev/dump-demo-site-data
Updated for new settings system, and added the start of some blog and tag data.
> New demo data

- README.md
- app/controllers/admin/news_controller.rb
- app/controllers/news_controller.rb
- app/helpers/main_site_helper.rb
- app/models/news_post.rb
- app/models/user.rb
- app/policies/admin/news_post_policy.rb
- app/views/admin/news/edit.html.erb
- app/views/admin/news/index.html.erb
- app/views/admin/news/new.html.erb
- app/views/shinycms/news/_right_sidebar_join.html.erb
- app/views/shinycms/news/_sidebar.html.erb
- app/views/shinycms/news/index.html.erb
- app/views/shinycms/news/month.html.erb
- app/views/shinycms/news/show.html.erb
- app/views/shinycms/news/year.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20200223184000_create_news_posts.rb
- db/schema.rb
- spec/factories/news_posts.rb
- spec/factories/users.rb
- spec/requests/admin/news_spec.rb
- spec/requests/news_spec.rb
Essentially a clone of the blog feature, with the sketchy multi-blog support ripped out.
> News section

- app/assets/stylesheets/halcyonic/shinycms.css
- app/assets/stylesheets/shinycms/admin_area.scss
- app/assets/stylesheets/shinycms/admin_toolbar.scss
- app/assets/stylesheets/shinycms/shinycms.css
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/blogs_controller.rb
- app/views/admin/includes/_footer.html.erb
- app/views/shinycms/includes/_footer.html.erb
- docs/code-of-conduct.md
> Update copyright notices, and start adding comment toppers to controllers

- .env.sample
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/admin/web_stats_controller.rb
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/users/sessions_controller.rb
- app/helpers/admin_area_helper.rb
- app/models/ahoy/event.rb
- app/models/ahoy/visit.rb
- app/models/user.rb
- app/policies/admin/ahoy_policy.rb
- app/views/admin/menu/_menu.html.erb
- app/views/admin/menu/_menu_stats.html.erb
- app/views/admin/web_stats/index.html.erb
- config/initializers/ahoy.rb
- config/locales/en.yml
- config/routes.rb
- db/demo-site-data/capabilities.yml
- db/demo-site-data/capability_categories.yml
- db/demo-site-data/user_capabilities.yml
- db/migrate/20200308113704_create_ahoy_visits_and_events.rb
- db/schema.rb
- db/seeds.rb
Lots of improvements to be made in the code for displaying/filtering/ordering the stats, but the basics are all in place now.
Merge early, merge often!
> Web stats (powered by Ahoy)

- .env.sample
- .gitignore
- Gemfile
- Gemfile.lock
- lib/tasks/admin.rake
- lib/tasks/feature.rake
Add dotenv gem, and modify rake tasks slightly to make use of it.
(Also, got over-excited and added a rake task to list feature flags.)
> Add dotenv

- app/controllers/admin/blog/posts_controller.rb
- app/controllers/admin/site_settings_controller.rb
- app/controllers/blogs_controller.rb
- app/helpers/main_site_helper.rb
- app/models/blog.rb
- app/views/admin/blogs/index.html.erb
- app/views/admin/menu/_menu_blogs.html.erb
`Model.all.first` is the same than `Model.first` and the methods which return a boolean normally ends with a question mark.
> Refactoring some parts to be more idiomatic code

- README.md
- app/views/admin/menu/_menu.html.erb
- app/views/admin/menu/_menu_other.html.erb
- db/demo-site-data/capabilities.yml
- db/demo-site-data/capability_categories.yml
- db/demo-site-data/user_capabilities.yml
Notably, the spam comment admin stuff seemed to be mismatched and hence not showing up.
> Resyncing capabilities across code, seeds, and demo site data

- app/controllers/admin/blog/posts_controller.rb
- app/controllers/admin/blogs_controller.rb
- app/controllers/admin/comments_controller.rb
- app/controllers/admin/email_stats_controller.rb
- app/controllers/admin/feature_flags_controller.rb
- app/controllers/admin/news_controller.rb
- app/controllers/admin/pages/sections_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/admin/site_settings_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/admin/web_stats_controller.rb
Authorise early, authorise often! ;)
> Make (first) authorise call as early as possible in each action

- app/models/user.rb
- app/views/shinycms/errors/_not_found.html.erb
- spec/requests/discussions_spec.rb
Some deprecation warnings have crept back in; most are in gems and fixed upstream so just waiting on releases (devise, sprockets, etc); a couple are actually in my code and are fixed here.
> Fix a few new warnings

- .overcommit.yml
- Gemfile
- app/controllers/admin/blog/posts_controller.rb
- app/controllers/admin/news_controller.rb
- app/policies/admin/default_policy.rb
- app/validators/safe_slug_validator.rb
- config/initializers/shinycms_settings.rb
- config/locales/en.yml
Changes required by the heady heights of the new 120 characters per line allowance.
Also, moved a validation fail message into the translations file, ftw.
> Rubocop line length change omg

- app/controllers/admin_controller.rb
- app/models/setting.rb
- app/models/setting_value.rb
- spec/mailer_previews/discussion_mailer_preview_spec.rb
- spec/mailers/discussion_spec.rb
- spec/models/page_section_spec.rb
- spec/models/page_spec.rb
- spec/requests/admin/site_settings_spec.rb
- spec/requests/admin_spec.rb
- spec/requests/pages_spec.rb
Hopefully a small improvement :)
> Change get/set helper methods on Settings model slightly

- package.json
- yarn.lock
Apparently this fixes whatever chaos JavaScript has unleashed on my CMS this week.
[I-have-no-idea-what-Im-doing.gif.js]
> yarn upgrade sledgehammer

- .pryrc
Unexpected victory!! :smiley: :tada:
> Fix PRETTY_PRY_PROMPT feature  #339

- app/controllers/admin/blog/posts_controller.rb
- app/controllers/admin/news_controller.rb
- app/controllers/tags_controller.rb
- app/views/shinycms/tags/show.html.erb
- config/locales/en.yml
- spec/requests/tags_spec.rb
I have no idea how I had 100% coverage without these??
> Add tests for Tags controller

- app/models/concerns/slug.rb
- spec/requests/admin/blog/posts_spec.rb
- spec/requests/admin/news_spec.rb
- spec/requests/admin/pages_spec.rb
Somehow managed not to push my last two commits on this branch before PR'ing and merging it. Let's try that again shall we? :roll_eyes:
> MOAR SLUGS

- spec/requests/admin/blog/posts_spec.rb
- spec/requests/admin/blogs_spec.rb
- spec/requests/admin/news_spec.rb
- spec/requests/admin/users_spec.rb
- spec/requests/discussions_spec.rb
- spec/requests/user_spec.rb
> Use the Culture ship name version of Faker in more places

- app/models/blog.rb
- app/models/blog_post.rb
- app/models/capability.rb
- app/models/capability_category.rb
- app/models/comment.rb
- app/models/concerns/posted_at.rb
- app/models/concerns/teaser.rb
- app/models/discussion.rb
- app/models/do_not_contact.rb
- app/models/email_recipient.rb
- app/models/feature_flag.rb
- app/models/insert_element.rb
- app/models/insert_set.rb
- app/models/mailing_list.rb
- app/models/news_post.rb
- app/models/page.rb
- app/models/page_element.rb
- app/models/page_section.rb
- app/models/page_template.rb
- app/models/page_template_element.rb
- app/models/setting.rb
- app/models/setting_value.rb
- app/models/subscription.rb
- app/models/theme.rb
- spec/models/blog_spec.rb
Mostly just moving all the code around to be in the same order in each file, and using symbols instead of strings everywhere.
Refactored some stuff around models with a posted_at date (so, news_post and blog_post currently) out into a concern.
> Tidy up models

- Gemfile
- Gemfile.lock
- app/controllers/discussions_controller.rb
- app/models/comment.rb
- app/models/user.rb
- app/views/shinycms/discussions/_comment.html.erb
- app/views/shinycms/discussions/_comment_moderation_links.html.erb
- app/views/shinycms/discussions/_comment_vote_up.html.erb
- app/views/shinycms/discussions/_comment_vote_up_down.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20200630142104_acts_as_votable_migration.rb
- db/schema.rb
- db/seeds.rb
- docs/Developers/Progress.md
- docs/Developers/TODO.md
- spec/models/comment_spec.rb
- spec/requests/discussions_spec.rb
- spec/support/shared_examples/voteable_example.rb
> Votes (likes) feature

- app/controllers/admin/blog/posts_controller.rb
- app/controllers/admin/blogs_controller.rb
- app/controllers/admin/news_controller.rb
- app/controllers/admin/pages/sections_controller.rb
- app/controllers/admin/pages/templates_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/admin/users_controller.rb
- app/helpers/admin_area_helper.rb
(Golfing meaningless code-quality metrics, tra la la)
> Add wrapper method for setting flash notice and redirecting

- README.md
- docs/Developers/Progress.md
- yarn.lock
Making README more about the project and less about the metaproject - moved the meta stuff into the Developer docs mostly.
Took the newlines out of few .md files to see how that works out for me in practice.
> Doc tweaks

- app/controllers/application_controller.rb
- app/models/capability_category.rb
- app/models/plugin.rb
- app/models/theme.rb
- app/models/user.rb
- app/policies/admin/default_policy.rb
- docs/Developers/Plugins.md
- plugins/ShinyForms/app/models/shiny_forms/form.rb
- plugins/ShinyForms/app/policies/admin/form_policy.rb
- plugins/ShinyForms/app/policies/shiny_forms/admin/form_policy.rb
- plugins/ShinyForms/config/locales/en.yml
- plugins/ShinyForms/db/seeds.rb
- plugins/ShinyForms/lib/shiny_forms.rb
- plugins/ShinyForms/shiny_forms.gemspec
- plugins/ShinyForms/spec/factories/users.rb
... to make it easier to add the next plugin
> Refactor forms plugin and supporting code

- spec/mailer_previews/discussion_mailer_preview_spec.rb
- spec/models/discussion_spec.rb
- spec/requests/admin/comments_spec.rb
- spec/requests/discussions_spec.rb
- spec/requests/votes_spec.rb
- spec/support/shared_examples/admin_redirect_example.rb
- spec/support/shared_examples/voteable_voter_example.rb
> Adding skipped news tests back in (they will fail spectacularly)

- app/controllers/blogs_controller.rb
- app/models/blog.rb
- app/models/concerns/shiny_post.rb
- app/models/concerns/shiny_slug_in_month.rb
- plugins/ShinyNews/app/controllers/shiny_news/news_controller.rb
Also, tweak method names to be clearer.
> Use .all_month and .all_year to build date ranges for blog/news posts

- config/application.rb
- config/initializers/i18n.rb
> Move i18n config (locale file paths etc) into an initializer

- plugins/ShinyForms/app/views/shiny_forms/admin/menu/_section.html.erb
- plugins/ShinyNews/app/views/shiny_news/admin/menu/_section.html.erb
I think these must have got regressed somehow, they were loading a few days ago but not today :raised_eyebrow:
> Fix plugin admin menu capability checks and path helpers

- yarn.lock
... to fix b0rk after acorn upgrade.
> Bumping all JavaScript dependencies

- .circleci/config.yml
- app/controllers/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/helpers/main_site_helper.rb
- app/models/user.rb
- app/views/admin/blog/posts/index.html.erb
- app/views/admin/includes/_user_menu.html.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/new.html.erb
- app/views/shinycms/devise/registrations/edit.html.erb
- app/views/shinycms/discussions/comment/_form.html.erb
- db/migrate/20200813090405_change_display_name_to_public_name.rb
- db/schema.rb
- docs/Developers/TODO.md
- plugins/ShinyNews/app/views/shiny_news/admin/news/index.html.erb
- plugins/ShinyProfiles/app/views/shiny_profiles/profiles/show.html.erb
- spec/requests/user_spec.rb
Also, rename display_name to public_name, for consistency.
> Use user.name instead of user_display_name helper

- app/controllers/application_controller.rb
- app/controllers/tags_controller.rb
- app/helpers/admin_area_helper.rb
- app/helpers/main_site_helper.rb
- app/models/concerns/shiny_post.rb
- app/models/concerns/shiny_slug_in_month.rb
- app/models/concerns/shiny_slug_in_section.rb
- app/models/plugin.rb
- app/views/admin/includes/_admin_toolbar.html.erb
- app/views/admin/menu/_menu.html.erb
- app/views/shinycms/menu/_menu.html.erb
- config/routes.rb
- db/seeds.rb
- plugins/ShinyProfiles/Gemfile.lock
And add some more useful methods to the objects.
> Pass Plugin objects around more instead of just their names

- app/views/admin/menu/_menu.html.erb
- app/views/admin/users/_edit_capabilities.html.erb
- config/locales/en.yml
- config/routes.rb
- db/seeds.rb
This PR also gets rid of the unused 'admin dashboard' menu item and capability.
> Add Sidekiq web UI

- db/demo_data.rb
Moving pages into a more compact formation on the menu, to leave room for the other features :)
> Changes to demo data

- app/models/user_capability.rb
- db/migrate/20201009164412_add_deleted_at_to_user_capabilities.rb
- db/schema.rb
> Soft delete for user capabilities

- app/controllers/main_controller.rb
- app/controllers/tags_controller.rb
- app/controllers/votes_controller.rb
- app/helpers/admin_area_helper.rb
- app/helpers/shiny_plugin_helper.rb
- app/models/application_record.rb
- app/models/concerns/shiny_post.rb
- app/models/shiny_plugin.rb
- app/models/user.rb
- config/routes.rb
- db/seeds.rb
- docs/Developers/Plugins.md
- plugins/ShinyPages/app/models/shiny_pages/page.rb
- plugins/ShinyPages/app/models/shiny_pages/page_element.rb
- plugins/ShinyPages/app/models/shiny_pages/section.rb
- plugins/ShinyProfiles/app/helpers/shiny_profiles/main_site_helper.rb
- spec/models/shiny_plugin_spec.rb
Also added a bit more documentation for plugin authors.
> Rename Plugin model to ShinyPlugin

- package.json
- yarn.lock
Might have figured it out this time though. I hope.
> The Node Module That Would Not Die

- app/models/concerns/shiny_post.rb
- plugins/ShinyBlog/app/controllers/shiny_blog/admin/blog_posts_controller.rb
…rather than the individual admin controllers
> Call the feed generator job from the ShinyPost concern

- app/controllers/main_controller.rb
- app/helpers/shiny_plugin_helper.rb
- app/models/shiny_post_atom_feed.rb
- app/models/shiny_post_atom_feed_entry.rb
- app/views/shinycms/includes/_head.html.erb
- app/views/themes/halcyonic/includes/_head.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- docs/env.sample
- plugins/ShinyBlog/app/views/shiny_blog/includes/_head_part.html.erb
- plugins/ShinyNews/app/views/shiny_news/includes/_head_part.html.erb
- spec/models/shiny_post_atom_feed_spec.rb
- spec/requests/main_spec.rb
(if ENV vars exist)
Some slightly odd fiddling with the feed link protocol in here; this is to do with my production hosting set-up, sorry :)
> Write Atom feeds to AWS S3 bucket

- plugins/ShinyBlog/app/views/shiny_blog/blog/index.html.erb
- plugins/ShinyBlog/app/views/shiny_blog/blog/show.html.erb
- plugins/ShinyNews/app/views/shiny_news/news/index.html.erb
- plugins/ShinyNews/app/views/shiny_news/news/show.html.erb
- vendor/assets/stylesheets/halcyonic/shinycms.scss
(float right, 400px max in either direction)
> Add a default style for images in blog/news posts in Halcyonic theme

- db/seeds.rb
- db/seeds/capabilities.rb
- db/seeds/feature_flags.rb
- db/seeds/settings.rb
- plugins/ShinyBlog/db/seeds.rb
- plugins/ShinyForms/db/seeds.rb
- plugins/ShinyLists/db/seeds.rb
- plugins/ShinyNews/db/seeds.rb
- plugins/ShinyNewsletters/db/seeds.rb
- plugins/ShinyPages/db/seeds.rb
- plugins/ShinyProfiles/db/seeds.rb
- plugins/ShinySearch/db/seeds.rb
Split out capabilities, feature flags, and settings, from main seeds file into db/seeds/*.rb
> Refactor seeds

- app/controllers/discussions_controller.rb
- app/controllers/users/registrations_controller.rb
- app/helpers/akismet_helper.rb
- app/helpers/recaptcha_helper.rb
- app/helpers/shiny_discussion_helper.rb
- app/views/admin/users/_edit_capabilities.html.erb
- app/views/shinycms/devise/registrations/new.html.erb
- app/views/shinycms/discussions/comment/_form.html.erb
- app/views/shinycms/includes/_recaptcha_tags.html.erb
- app/views/themes/halcyonic/shiny_pages/pages/contact-form.html.erb
- config/locales/en.yml
- db/seeds/settings.rb
- docs/Developers/TODO.md
- docs/env.sample
- lib/tasks/demo.rake
- plugins/ShinyForms/app/controllers/shiny_forms/forms_controller.rb
- plugins/ShinyLists/app/views/shiny_lists/admin/user/_edit_capabilities.html.erb
- plugins/ShinyNewsletters/app/views/shiny_newsletters/admin/user/_edit_capabilities.html.erb
- spec/requests/site_settings_spec.rb
Mostly around reCAPTCHA and Akismet.
> Assorted minor bugfixes and refactoring

- Gemfile.lock
- config/initializers/version.rb
- docs/release-notes.md
- plugins/ShinyBlog/lib/shiny_blog/version.rb
- plugins/ShinyForms/lib/shiny_forms/version.rb
- plugins/ShinyInserts/lib/shiny_inserts/version.rb
- plugins/ShinyLists/lib/shiny_lists/version.rb
- plugins/ShinyNews/lib/shiny_news/version.rb
- plugins/ShinyNewsletters/lib/shiny_newsletters/version.rb
- plugins/ShinyPages/lib/shiny_pages/version.rb
- plugins/ShinyProfiles/lib/shiny_profiles/version.rb
- plugins/ShinySearch/lib/shiny_search/version.rb
Bump versions and add release notes, ready to tag as this month's release.
> Release 20.11

- Gemfile.lock
- app/controllers/admin/comments_controller.rb
- app/controllers/discussions_controller.rb
- app/views/admin/comments/index.html.erb
- app/views/admin/includes/_search.html.erb
- app/views/shinycms/discussions/_comment.html.erb
- config/routes.rb
- spec/requests/admin/comments_spec.rb
- spec/requests/admin/email_stats_spec.rb
- spec/requests/admin/web_stats_spec.rb
Exposure to the wilds of the Internet has revealed a few bugs in the spam flagging and moderation code; this PR fixes them.
> Comment moderation bug fixes

- config/locales/en.yml
- db/seeds/feature_flags.rb
- spec/requests/user_spec.rb
> Pluralise registration(s) flag to match comments and forms flags

- db/demo_data.rb
- db/migrate/20201206144100_add_missing_indexes.rb
- db/schema.rb
- docs/Developers/Notes/needs-indexing.md
- docs/Developers/TODO.md
- docs/Developers/demo-data.md
- plugins/ShinyProfiles/app/models/shiny_profiles/profile.rb
Also includes some minor tweaks to demo data.
> Add missing indexes

- .rubocop.yml
- Gemfile.lock
- README.md
- docs/Developers/TODO.md
Getting rid of some incidental noise between main and the ruby 3.0.0 branch; gem bumps and minor doc tweaks.
> Reduce diff to 3.0.0

- Gemfile
- Gemfile.lock
Also, build Gemfile.lock with it (using tools/shiny-bundle-install) to fix #803
> Move bugsnag back into production block of Gemfile again

- db/migrate/20201227180916_add_service_name_to_active_storage_blobs.active_storage.rb
- db/migrate/20201227180917_create_active_storage_variant_records.active_storage.rb
- db/schema.rb
Adds and applies migrations required by newer versions of ActiveStorage.
> rails activestorage:update

- app/controllers/admin/web_stats_controller.rb
- docs/Developers/demo-data.md
- docs/Developers/in-progress.md
One expanded doc, and one more consistent controller - nothing drastic :)
> Minor pre release odds and ends

- app/models/concerns/shiny_html_template.rb
- app/models/concerns/shiny_mjml_template.rb
- plugins/ShinyForms/app/controllers/shiny_forms/admin/forms_controller.rb
- plugins/ShinyForms/app/models/shiny_forms/form.rb
Originally: https://github.com/denny/ShinyCMS-ruby/pull/802
> Use Enumerable#map instead of Enumerable#each + mutable Array

- app/models/concerns/shiny_html_template.rb
- app/models/concerns/shiny_mjml_template.rb
- docs/Developers/TODO.md
- docs/credits.md
- plugins/ShinyForms/app/controllers/shiny_forms/admin/forms_controller.rb
- plugins/ShinyForms/app/models/shiny_forms/form.rb
( This code is from #802 by @007lva )
> Refactor from arrays and loops to .collect in a few places

- .rubycritic.yml
- app/controllers/admin_controller.rb
- app/models/concerns/shiny_user_authentication.rb
- app/models/shiny_post_atom_feed_entry.rb
- app/models/theme.rb
- config/initializers/sessions.rb
- docs/Developers/TODO.md
- plugins/ShinyAccess/app/controllers/shiny_access/admin_controller.rb
- plugins/ShinyBlog/app/controllers/shiny_blog/admin/blog_posts_controller.rb
- plugins/ShinyBlog/app/controllers/shiny_blog/admin_controller.rb
- plugins/ShinyForms/app/controllers/shiny_forms/admin_controller.rb
- plugins/ShinyInserts/app/controllers/shiny_inserts/admin_controller.rb
- plugins/ShinyLists/app/controllers/shiny_lists/admin_controller.rb
- plugins/ShinyNews/app/controllers/shiny_news/admin/news_posts_controller.rb
- plugins/ShinyNews/app/controllers/shiny_news/admin_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin_controller.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/send.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin/pages_controller.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin_controller.rb
- plugins/ShinyProfiles/app/controllers/shiny_profiles/admin_controller.rb
Tidying up a few things highlighted by Ruby Critic...
> Various code quality tweaks

- app/controllers/admin/consent_versions_controller.rb
Part of the ongoing process of trying to improve files that score high in Ruby Critic... particularly those that don't seem to deserve it, like this one.
> Minor tweaks to admin controller for consent versions

- docs/Developers/TODO.md
- plugins/ShinyPages/app/controllers/shiny_pages/pages_controller.rb
- plugins/ShinyPages/spec/requests/pages_spec.rb
Fixes two bugs - URLs with nested non-existent sections in them, and 404s for non-HTML URLs.
> Fix pages 404 handling

- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/views/admin/users/new.html.erb
- spec/requests/admin/users_controller_spec.rb
Move search method implementation into model. Remove some params handled by ShinyProfiles now. Better test for error handling in .update method.
> Tidying user admin controller

- app/controllers/admin/comments_controller.rb
- app/controllers/admin/consent_versions_controller.rb
- app/controllers/admin/email_recipients_controller.rb
- app/models/comment.rb
- app/models/consent_version.rb
- app/models/email_recipient.rb
- docs/Developers/TODO.md
- plugins/ShinyBlog/app/controllers/shiny_blog/admin/blog_posts_controller.rb
- plugins/ShinyBlog/app/models/shiny_blog/post.rb
- plugins/ShinyForms/app/controllers/shiny_forms/admin/forms_controller.rb
- plugins/ShinyForms/app/models/shiny_forms/form.rb
- plugins/ShinyLists/app/controllers/shiny_lists/admin/lists_controller.rb
- plugins/ShinyLists/app/models/shiny_lists/list.rb
- plugins/ShinyNews/app/controllers/shiny_news/admin/news_posts_controller.rb
- plugins/ShinyNews/app/models/shiny_news/post.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/editions_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/sends_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/templates_controller.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/edition.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/send.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/template.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin/templates_controller.rb
- plugins/ShinyPages/app/models/shiny_pages/template.rb
Most of them; I left a few potentially awkward ones to pick up another day. 🙂 
These still need expanding in many cases, but at least they're in a better place in the code now.
> Move admin search implementations from controllers to models

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/admin/includes/_user_menu.html.erb
This allows us to unpin and bump Blazer
> Prevent Blazer from removing all of the ShinyCMS helpers

- plugins/ShinyForms/app/models/shiny_forms/form.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/editions_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/sends_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin/templates_controller.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/template.rb
- plugins/ShinyNewsletters/spec/requests/admin/editions_spec.rb
- plugins/ShinyNewsletters/spec/requests/admin/templates_spec.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin/pages_controller.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin/templates_controller.rb
- plugins/ShinyPages/app/models/shiny_pages/template.rb
- plugins/ShinyPages/config/locales/en.yml
- plugins/ShinyPages/spec/requests/admin/pages_spec.rb
- plugins/ShinyPages/spec/requests/admin/templates_spec.rb
Trying to reduce complexity and increase consistency in a few places highlighted by Ruby Critic (mostly ShinyPages and ShinyNewsletters admin controllers)
* Use before actions to stash instance variables
* Get rid of exception-catching mess around some destroy methods
* Test destroy method failure by adding dependent objects instead
* Factor out some duplicate method calls
* Use safe navigation operator rather than explicit null checks
> Various code quality improvements

- docs/Developers/TODO.md
- docs/Developers/in-progress.md
I should probably herd most of this into issues or a project board or something...
> Shift stuff from top of TODO down into appropriate sections

- db/seeds/blazer.rb
- plugins/ShinyProfiles/app/views/shiny_profiles/profiles/edit.html.erb
None of the tests need this data loaded, so let's waste time loading it.
> Don't load Blazer seed data for tests

- app/views/admin/includes/_breadcrumbs.html.erb
- app/views/admin/includes/_head.html.erb
- spec/requests/admin/stats_spec.rb
Getting rid of an old FIXME comment :)
> Fix the page title when viewing embedded Blazer pages

- spec/i18n_spec.rb
- spec/spec_helper.rb
I was hoping to figure out the MJML network activity thing on this branch, but I did not. These trivial odds and ends seem worth keeping though.
> Test speed

- plugins/ShinyCMS/spec/requests/shinycms/users/sessions_controller_spec.rb
- plugins/ShinyForms/spec/requests/forms_spec.rb
I don't know how these managed to hide for this long!
> Add main_app. before root_path helper calls

- plugins/ShinyBlog/app/models/shiny_blog/post.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/shiny_post.rb
- plugins/ShinyNews/app/models/shiny_news/post.rb
Moved admin search method out of two models, into concern, and tweaked scopes a little.
> Minor improvements to ShinyPosts

- .rubocop_todo.yml
- config/routes.rb
- db/seeds.rb
- db/seeds/blazer.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/application_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/main_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/tags_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/votes_controller.rb
- plugins/ShinyCMS/app/helpers/shinycms/admin_area_helper.rb
- plugins/ShinyCMS/app/helpers/shinycms/plugins_helper.rb
- plugins/ShinyCMS/app/helpers/shinycms/users_helper.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/shiny_post.rb
- plugins/ShinyCMS/app/models/shinycms/application_record.rb
- plugins/ShinyCMS/app/models/shinycms/user.rb
- plugins/ShinyCMS/lib/shinycms.rb
- plugins/ShinyCMS/spec/models/shinycms/plugins_components_spec.rb
- plugins/ShinyPages/app/models/shiny_pages/page.rb
- plugins/ShinyPages/app/models/shiny_pages/page_element.rb
- plugins/ShinyPages/app/models/shiny_pages/section.rb
- plugins/ShinyPages/app/validators/shiny_pages/top_level_slug_validator.rb
- plugins/ShinyProfiles/app/helpers/shiny_profiles/main_site_helper.rb
- plugins/ShinyProfiles/app/models/shiny_profiles/link.rb
- plugins/ShinyProfiles/app/models/shiny_profiles/profile.rb
- plugins/ShinySEO/app/models/shiny_seo/sitemap.rb
Instantiate plugin set at startup and stash it at the top-level of the core module, for re-use throughout.
> ShinyCMS::Plugins.all -> ShinyCMS.plugins

- README.md
- docs/Developers/TODO.md
- docs/Developers/in-progress.md
- docs/tldr.md
- tools/rspec-sample-pack
More to do still, but it's a start...
> Start updating docs in line with core plugin refactor

- db/demo_site_data.rb
- plugins/ShinyCMS/app/lib/shinycms/demo_site_data.rb
This is _definitely_ not the right way to do this, in the same way that explosives are not the right way to open a window, but - similarly - it does work.
I don't understand why a lambda isn't working in the offending validator. I may have to consult a grown-up.
> Fix demo data import

- plugins/ShinyCMS/app/lib/shinycms/demo_site_data.rb
- plugins/ShinyCMS/app/models/shinycms/theme.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/template.rb
- plugins/ShinyPages/app/models/shiny_pages/template.rb
Figured out the lambda syntax I wanted, got rid of the crazy reloading of the models. Yay.
> Fix demo data import properly

- app/controllers/application_controller.rb
- app/policies/mailer_preview_policy.rb
- config/environments/development.rb
- config/routes.rb
- db/seeds/capabilities.rb
- plugins/ShinyAccess/config/routes.rb
- plugins/ShinyBlog/config/routes.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin_controller.rb
- plugins/ShinyCMS/app/views/shinycms/admin/menu/_coverband.html.erb
- plugins/ShinyCMS/app/views/shinycms/admin/menu/_sidekiq_web.html.erb
- plugins/ShinyCMS/app/views/shinycms/admin/users/_edit_capabilities.html.erb
- plugins/ShinyCMS/config/locales/en.yml
- plugins/ShinyCMS/config/routes.rb
- plugins/ShinyCMS/config/routes/admin_area.rb
- plugins/ShinyCMS/config/routes/mount_other_engines.rb
- plugins/ShinyCMS/config/routes/mount_other_engines_in_main_app.rb
- plugins/ShinyCMS/lib/import_routes.rb
- plugins/ShinyCMS/spec/factories/shinycms/users.rb
- plugins/ShinyCMS/spec/requests/shinycms/admin/blazer_embed_spec.rb
- plugins/ShinyCMS/spec/requests/shinycms/admin/stats_controller_spec.rb
- plugins/ShinyForms/config/routes.rb
- plugins/ShinyLists/config/routes.rb
- plugins/ShinyNews/config/routes.rb
- plugins/ShinyNewsletters/config/routes.rb
- plugins/ShinyPages/config/routes.rb
- public/js/ckeditor/config.js
- spec/mailer_previews/discussion_mailer_preview_spec.rb
- spec/mailer_previews/rails_email_preview_spec.rb
- spec/mailer_previews/user_mailer_preview_spec.rb
(Blazer, CKEditor, Coverband, LetterOpenerWeb, Rails Email Preview, Sidekiq Web.)
> Move gem engines to /admin/tools/{name} URLs and :tools capability category

- Gemfile
- Gemfile.lock
- config/webpack/environment.js
- plugins/ShinyBlog/app/views/shiny_blog/blog/index.html.erb
- plugins/ShinyBlog/app/views/shiny_blog/blog/month.html.erb
- plugins/ShinyCMS/shinycms.gemspec
- plugins/ShinyNews/app/views/shiny_news/news/index.html.erb
- plugins/ShinyNews/app/views/shiny_news/news/month.html.erb
Also, pin simplecov in two places, to avoid incompatibility issues with CodeCov, RubyCritic, etc.
> Fix missing jQuery, and get rid of duplicate text on blog and news index pages

- plugins/ShinyCMS/app/mailer_previews/shinycms/user_mailer_preview.rb
- plugins/ShinyCMS/app/mailers/shinycms/email_recipient_mailer.rb
- plugins/ShinyCMS/app/mailers/shinycms/user_mailer.rb
- plugins/ShinyCMS/app/models/concerns/shinycms/has_email.rb
- plugins/ShinyCMS/config/initializers/devise.rb
- plugins/ShinyCMS/spec/factories/shinycms/users.rb
- plugins/ShinyCMS/spec/mailers/shinycms/user_mailer_spec.rb
- plugins/ShinyCMS/spec/requests/shinycms/users/registrations_controller_spec.rb
- plugins/ShinyCMS/spec/requests/shinycms/users/sessions_controller_spec.rb
- plugins/ShinyCMS/spec/support/shared_examples/shinycms/has_email_example.rb
- plugins/ShinyNewsletters/app/mailers/shiny_newsletters/newsletter_mailer.rb
More consistency between them, and with related code.
Also added a user mailer spec here.
> Tidy up mailers a bit

- plugins/ShinyCMS/lib/import_routes.rb
- plugins/ShinyCMS/spec/lib/import_routes_spec.rb
This is a lot smaller now, a bit simpler, and probably a bit safer too 🤔
> Tidy up import-routes method a lot, and add tests

- plugins/ShinyAccess/lib/shiny_access/engine.rb
- plugins/ShinyBlog/lib/shiny_blog/engine.rb
- plugins/ShinyCMS/lib/shinycms/engine.rb
- plugins/ShinyForms/lib/shiny_forms/engine.rb
- plugins/ShinyInserts/lib/shiny_inserts/engine.rb
- plugins/ShinyLists/lib/shiny_lists/engine.rb
- plugins/ShinyNews/lib/shiny_news/engine.rb
- plugins/ShinyNewsletters/lib/shiny_newsletters/engine.rb
- plugins/ShinyPages/lib/shiny_pages/engine.rb
- plugins/ShinyProfiles/lib/shiny_profiles/engine.rb
- plugins/ShinySEO/lib/shiny_seo/engine.rb
- plugins/ShinySearch/lib/shiny_search/engine.rb
> FactoryBot was loaded conditionally for very good reason, i.e. it's not present in production.

- Gemfile
- Gemfile.lock
(and try to stop dependabot PRing ahoy 2.0)
> bundle update 

- plugins/ShinyAccess/app/controllers/shiny_access/admin_controller.rb
- plugins/ShinyBlog/app/controllers/shiny_blog/admin_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/base_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/comments_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/consent_versions_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/discussions_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/email_recipients_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/email_stats_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/feature_flags_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/root_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/site_settings_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/users_controller.rb
- plugins/ShinyCMS/app/controllers/shinycms/admin/web_stats_controller.rb
- plugins/ShinyCMS/app/helpers/shinycms/admin_area_helper.rb
- plugins/ShinyCMS/config/initializers/ckeditor.rb
- plugins/ShinyCMS/config/routes/admin_area.rb
- plugins/ShinyCMS/config/routes/admin_page_not_found.rb
- plugins/ShinyCMS/spec/requests/shinycms/admin_controller_spec.rb
- plugins/ShinyForms/app/controllers/shiny_forms/admin_controller.rb
- plugins/ShinyInserts/app/controllers/shiny_inserts/admin_controller.rb
- plugins/ShinyLists/app/controllers/shiny_lists/admin_controller.rb
- plugins/ShinyNews/app/controllers/shiny_news/admin_controller.rb
- plugins/ShinyNewsletters/app/controllers/shiny_newsletters/admin_controller.rb
- plugins/ShinyPages/app/controllers/shiny_pages/admin_controller.rb
- plugins/ShinyProfiles/app/controllers/shiny_profiles/admin_controller.rb
- plugins/ShinySEO/app/controllers/shiny_seo/admin_controller.rb
> Move ShinyCMS::AdminController to ShinyCMS::Admin::BaseController

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/lib/shinycms.rb
- plugins/ShinyCMS/shinycms.gemspec
As they finally released that fix!
> Back to the standard ActiveRecord session store gem

- db/seeds.rb
- plugins/ShinyCMS/db/seeds.rb
> Restore expected behaviour of `rails db:reset` et al

- plugins/ShinyCMS/config/initializers/rails_email_preview.rb
- plugins/ShinyCMS/spec/requests/shinycms/admin/tools/rails_email_preview_spec.rb
Little bit of extra config required now that this is in the core plugin.
> Fix RailsEmailPreview layout

- plugins/ShinyNewsletters/app/jobs/shiny_newsletters/send_to_list_job.rb
- plugins/ShinyNewsletters/app/models/shiny_newsletters/send.rb
Another CodeClimate suggestion for simplification
> Add model methods to simplify job perform method

- plugins/ShinyForms/app/mailers/shiny_forms/form_mailer.rb
- plugins/ShinyForms/spec/mailers/shiny_forms/form_mailer_spec.rb
- plugins/ShinyLists/lib/shiny_lists/engine.rb
- plugins/ShinyNewsletters/lib/shiny_newsletters/engine.rb
- plugins/ShinySEO/lib/shiny_seo/engine.rb
And tidy up a few minor inconsistencies
> Add a test for missing form handler email template

- plugins/ShinyCMS/app/models/shinycms/plugins.rb
Dropped some unused delegations, refactored some complicated methods.
> Refactoring in Plugins code

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/spec/spec_helper.rb
Testing is srs bsns, but smiling is allowed.
> Add Pacman formatter for RSpec

- plugins/ShinyAccess/app/components/shiny_access/application_component.rb
- plugins/ShinyBlog/app/components/shiny_blog/application_component.rb
- plugins/ShinyCMS/app/components/shinycms/application_component.rb
- plugins/ShinyCMS/app/mailers/shinycms/application_mailer.rb
- plugins/ShinyCMS/app/mailers/shinycms/setup_for_base_mailer.rb
- plugins/ShinyCMS/app/public/components/shinycms/base_component.rb
- plugins/ShinyCMS/app/public/mailers/shinycms/base_mailer.rb
- plugins/ShinyForms/app/components/shiny_forms/application_component.rb
- plugins/ShinyLists/app/components/shiny_lists/application_component.rb
- plugins/ShinyNews/app/components/shiny_news/application_component.rb
- plugins/ShinyNewsletters/app/components/shiny_newsletters/application_component.rb
- plugins/ShinyPages/app/components/shiny_pages/application_component.rb
* Added a layer of indirection for plugin components similar to other entities (via ApplicationComponent in the plugin, inheriting from BaseComponent in the core)
* Changed how mailer inheritance is structured for mailers within the core plugin, to be more consistent with how feature plugin mailers inherit from core
> Refactoring inheritance

- package.yml
- plugins/ShinyAccess/package.yml
- plugins/ShinyBlog/app/models/shiny_blog/post.rb
- plugins/ShinyBlog/package.yml
- plugins/ShinyCMS/app/public/models/concerns/shinycms/post.rb
- plugins/ShinyCMS/deprecated_references.yml
- plugins/ShinyCMS/package.yml
- plugins/ShinyForms/package.yml
- plugins/ShinyInserts/package.yml
- plugins/ShinyLists/package.yml
- plugins/ShinyNews/app/models/shiny_news/post.rb
- plugins/ShinyNews/package.yml
- plugins/ShinyNewsletters/package.yml
- plugins/ShinyPages/package.yml
- plugins/ShinyProfiles/package.yml
- plugins/ShinySEO/package.yml
- plugins/ShinySearch/package.yml
Mostly just tidying up config files, plus one boundary fix.
> Spring clean Packwerk

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/app/public/controllers/concerns/shinycms/controller_base.rb
- plugins/ShinyCMS/app/views/shinycms/admin/includes/_pager.html.erb
- plugins/ShinyCMS/app/views/shinycms/includes/_newer_older_pager.html.erb
- plugins/ShinyCMS/config/initializers/assets.rb
- plugins/ShinyCMS/config/routes/tools.rb
- plugins/ShinyCMS/db/seeds/capabilities.rb
- plugins/ShinyCMS/lib/tasks/demo_site.rake
- plugins/ShinyCMS/shinycms.gemspec
- plugins/ShinyInserts/spec/requests/shiny_inserts/admin/inserts_controller_spec.rb
- yarn.lock
Some fixes for new rubocop complaints, also an unrelated tweak to demo site data.
Unlocked or updated a few pinned gems here, including Pagy which had changed its method signatures a while back.
> Bump gems and node modules

- plugins/ShinyCMS/app/assets/config/shinycms_manifest.js
- plugins/ShinyCMS/config/initializers/assets.rb
> Put config to load admin area JS in correct file

- plugins/ShinyAccess/app/models/shiny_access/membership.rb
Use .all_day to tidy up some date-range code.
> Neater date range operations

- plugins/ShinyBlog/spec/jobs/shiny_blog/build_atom_feed_job_spec.rb
- plugins/ShinyNews/spec/jobs/shiny_news/build_atom_feed_job_spec.rb
Use more specific methods to get the path for the writing test files.
> Update test code that needs paths for feed files

- Gemfile
Change in how dotenv is loaded... old syntax will be deprecated at some point.
> Fix loading of dotenv

- Gemfile.lock
- packwerk.yml
- plugins/ShinyCMS/shinycms.gemspec
denny@rocinante:~/shinycms$ purr
Sat 24 Feb 16:07:39 GMT 2024
📦 Packwerk is running validation...
📦 Finished in 0.61 seconds
Validation successful 🎉
📦 Packwerk is inspecting 612 files
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
📦 …
> Re-add and re-enable all Packwerk package boundary enforcement features

- plugins/ShinyCMS/app/public/models/concerns/shinycms/post.rb
- plugins/ShinyNews/spec/models/shiny_news/post_spec.rb
... and include the rails helper consistently in both plugin engines.
> Fix rails merge deprecation warnings

- Gemfile.lock
Fixes for CVE-2025-27219 and CVE-2025-27220
> Update cgi gem

- Gemfile
- Gemfile.lock
Fixes https://github.com/rack/rack/security/advisories/GHSA-7wqh-767x-r66v
> Update rack gem

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/.rubocop.yml
- plugins/ShinyCMS/spec/other/demo_site_task_spec.rb
> Change to Prism parser

- Gemfile
- Gemfile.lock
- plugins/ShinyCMS/app/views/shinycms/includes/_newer_older_pager.html.erb
Step 1 in the pagy update saga. Still got several steps left to go before I'm up-to-date though.
> Bump pagy from 6.5 to 7.0

- plugins/ShinyCMS/config/initializers/rack_attack.rb
Block (probably Wordpress again) malformed new password requests too.
> More WP-blocking rack-attack rules

- plugins/ShinyAccess/spec/helpers/shiny_access/main_site_helper_spec.rb
- plugins/ShinyAccess/spec/models/shiny_access/group_spec.rb
- plugins/ShinyAccess/spec/models/shiny_access/membership_spec.rb
- plugins/ShinyBlog/spec/jobs/shiny_blog/build_atom_feed_job_spec.rb
- plugins/ShinyBlog/spec/models/shiny_blog/post_spec.rb
- plugins/ShinyCMS/.rubocop_todo.yml
- plugins/ShinyForms/spec/mailers/shiny_forms/form_mailer_spec.rb
- plugins/ShinyForms/spec/models/shiny_forms/form_spec.rb
- plugins/ShinyInserts/spec/models/shiny_inserts/element_spec.rb
- plugins/ShinyLists/spec/helpers/shiny_lists/main_site_helper_spec.rb
- plugins/ShinyLists/spec/models/shiny_lists/list_spec.rb
- plugins/ShinyLists/spec/models/shiny_lists/subscription_spec.rb
- plugins/ShinyNews/spec/jobs/shiny_news/build_atom_feed_job_spec.rb
- plugins/ShinyNewsletters/spec/jobs/shiny_newsletters/send_to_list_spec.rb
- plugins/ShinyNewsletters/spec/jobs/shiny_newsletters/send_to_subscriber_spec.rb
- plugins/ShinyNewsletters/spec/models/shiny_newsletters/edition_element_spec.rb
- plugins/ShinyNewsletters/spec/models/shiny_newsletters/edition_spec.rb
- plugins/ShinyNewsletters/spec/models/shiny_newsletters/send_spec.rb
- plugins/ShinyNewsletters/spec/models/shiny_newsletters/template_element_spec.rb
- plugins/ShinyNewsletters/spec/models/shiny_newsletters/template_spec.rb
- plugins/ShinyPages/spec/models/shiny_pages/page_element_spec.rb
- plugins/ShinyPages/spec/models/shiny_pages/section_spec.rb
- plugins/ShinyPages/spec/models/shiny_pages/template_element_spec.rb
- plugins/ShinyPages/spec/models/shiny_pages/template_spec.rb
- plugins/ShinyProfiles/spec/models/shiny_profiles/link_spec.rb
- plugins/ShinyProfiles/spec/models/shiny_profiles/profile_spec.rb
This pull request tries to solve the majority of the RSpec/DescribedClassModuleWrapping warnings. Fixes #1111
> Fixes #1111 (rubocop RSpec/DescribedClassModuleWrapping warnings) 

- docs/Contributors.md
Missed the 's' off of Manuel's name!
> Fix typo in Contributor list

- Gemfile.lock
Not sure what I did wrong here but the upgrade seems incomplete... trying to nudge it right again.
> Ruby update, take 2

- plugins/ShinyCMS/app/models/shinycms/plugins.rb
Reverts denny/ShinyCMS-ruby#2109
This change blew up my test coverage. Reverting until I understand why and fix it.
> Revert "Fix dev reload errors"

- plugins/ShinyCMS/app/models/shinycms/plugins.rb
> Revert previous revert

- plugins/ShinyAccess/config/locales/pt.yml
- plugins/ShinyCMS/config/locales/devise.pt.yml
- plugins/ShinyCMS/config/locales/pt.yml
Partially resolve #2136 by providing a translation file for the ShinyAccess and ShinyCMS plugins
(Need to confirm in the webpage if the translation is successfull another time)
> Translation of the ShinyAccess and ShinyCMS plugins to portuguese

- plugins/ShinyAccess/config/locales/pt.yml
- plugins/ShinyCMS/config/locales/devise.pt.yml
- plugins/ShinyCMS/config/locales/pt.yml
All translation work by @MrBowmanXD , in case the problems merging it cause credit to be lost!
> Add Portuguguese translations for ShinyCMS and ShinyAccess plugins

- plugins/ShinyBlog/config/locales/pt.yml
As the title says added a translation file. Have to check for translation of "blog posts" to better this translation draft. Will review when i finish the translation process.
> Added translation file (portuguese) to the ShinyBlog plugin

- plugins/ShinyForms/config/locales/pt.yml
A new translation file was added to the project in order to continue the translation of the cms to portuguese.
> Translation for the ShinyForms plugin in portuguese

- plugins/ShinyCMS/config/locales/pt.yml
- plugins/ShinyForms/config/locales/pt.yml
Corrected the problem (before it was en: instead of pt:).
> Translation of ShinyForms plugin
